version: '3'
services:
  owntone:
    build:
      context: .
      dockerfile: ./.image/owntone/Dockerfile
    restart: always
      # network_mode: host
    ports:
      - "8080:3689"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"


