version: '3'
services:
  owntone:
    build:
      context: .
      dockerfile: ./.image/owntone/Dockerfile
    volumes:
      - .docker-data:/srv/music
    restart: always
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"


